package joqu.intervaltrainer;

public interface Const {
    String TAG = "joqu.intervaltrainer";
    String INTENT_EXTRA_TEMPLATE_ID_INT = "template_id";
    String INTENT_EXTRA_TEMPLATE_NAME_STRING = "template_name";
    String INTENT_EXTRA_GPS_LAT_DOUBLE = "latitude";
    String INTENT_EXTRA_GPS_LONG_DOUBLE = "longitude";
    String BROADCAST_COUNTDOWN_UPDATE = "joqu.intervaltrainer.COUNTDOWN_UPDATE";
    String BROADCAST_COUNTDOWN_DONE = "joqu.intervaltrainer.BROADCAST_COUNTDOWN_DONE";
    String BROADCAST_GPS_UPDATE = "joqu.intervaltrainer.SVC_UPDATE";
    String BROADCAST_SVC_STOP = "joqu.intervaltrainer.SVC_STOP";
    String BROADCAST_SVC_START = "joqu.intervaltrainer.SVC_START";
    String BROADCAST_SVC_PAUSE = "joqu.intervaltrainer.SVC_PAUSE";
    String INTENT_EXTRA_TIMELEFT_LONG = "millisUntilFinished";
    String BROADCAST_SVC_RESUME = "joqu.intervaltrainer.SVC_RESUME" ;
    String INTENT_EXTRA_DO_TIMER_BOOL = "timerOnly";
    String INTENT_EXTRA_DO_GPS_BOOL = "GPSOnly";
    String INTENT_EXTRA_DO_GPS_MOCK_BOOL = "GPSMock";
    String INTENT_EXTRA_GPS_DIST_FLOAT = "distance";
    String INTENT_EXTRA_GPS_SPEED_FLOAT = "speed";
    String INTENT_EXTRA_COUNTDOWN_TYPE_INT = "type";
    int MESSAGE_SESSION_DONE = 1;
    String BROADCAST_SVC_STOPPED = "joqu.intervaltrainer.SVC_STOPPED";
    String BROADCAST_SVC_STARTED = "joqu.intervaltrainer.SVC_STARTED";
    String BROADCAST_SVC_PAUSED = "joqu.intervaltrainer.SVC_PAUSED";
    long TIMER_COUNTDOWN_INTERVAL_LONG = 1000;
    long LOCATION_REQ_INTERVAL_INT = 5000;
    int DEBUG_INTERVAL_LEN_SEC = 60;
    String INTENT_EXTRA_COUNTDOWN_TOTAL_INT = "countdownTotal";
    String INTENT_EXTRA_COUNTDOWN_INDEX_INT = "countdownIndex";
    int INTERVAL_TYPE_RUN = 1;
    int INTERVAL_TYPE_WALK = 0;
    int INTERVAL_TYPE_COOLDOWN = 3;
    String APP_NAME = "joqu.intervaltrainer";
    String INTENT_EXTRA_GPS_TOTAL_DIST_FLOAT = "total_distance";
    int MESSAGE_SESSION_START = 2;
    int MESSAGE_INTERVAL_START = 3;
    int MESSAGE_INTERVAL_DONE = 4;
    int MESSAGE_TICK = 5;
}
